// Code generated by scripts/gen-swag; DO NOT EDIT.

package app

import (
	_ "voxel-gin-admin/internal/types/response"
	_ "voxel-gin-admin/internal/types/schema"
	_ "voxel-gin-admin/internal/domain/auth"
	_ "voxel-gin-admin/internal/domain/iam/account"
	_ "voxel-gin-admin/internal/domain/iam/client"
	_ "voxel-gin-admin/internal/domain/iam/dept"
	_ "voxel-gin-admin/internal/domain/iam/group"
	_ "voxel-gin-admin/internal/domain/iam/position"
	_ "voxel-gin-admin/internal/domain/iam/resource"
	_ "voxel-gin-admin/internal/domain/iam/role"
	_ "voxel-gin-admin/internal/domain/profile"
	_ "voxel-gin-admin/internal/domain/profile/identity"
	_ "voxel-gin-admin/internal/domain/sys/audit"
	_ "voxel-gin-admin/internal/domain/sys/banner"
	_ "voxel-gin-admin/internal/domain/sys/codegen"
	_ "voxel-gin-admin/internal/domain/sys/config"
	_ "voxel-gin-admin/internal/domain/sys/dict"
	_ "voxel-gin-admin/internal/domain/sys/feedback"
	_ "voxel-gin-admin/internal/domain/sys/file"
	_ "voxel-gin-admin/internal/domain/sys/job"
	_ "voxel-gin-admin/internal/domain/sys/notice"
	_ "voxel-gin-admin/internal/domain/sys/weak_password"
)
